package main

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestIndexHandler(t *testing.T) {
	// 1. Create a mock HTTP request to send to the handler.
	// We can use an arbitrary path for the test.
	req, err := http.NewRequest(http.MethodGet, "/some/path", nil)
	if err != nil {
		t.Fatal(err) // Fail the test if the request can't be created
	}

	// 2. Create a ResponseRecorder (a mock http.ResponseWriter)
	// to record the response generated by the handler.
	rr := httptest.NewRecorder()

	// 3. Call the handler function directly with the mock recorder and request.
	IndexHandler(rr, req)

	// 4. Check the status code the handler wrote.
	if status := rr.Code; status != http.StatusOK {
		t.Errorf("handler returned wrong status code: got %v want %v",
			status, http.StatusOK)
	}

	// 5. Check the response body the handler wrote.
	expected := "Hello, you've requested: /some/path\n"
	if rr.Body.String() != expected {
		t.Errorf("handler returned unexpected body: got %v want %v",
			rr.Body.String(), expected)
	}
}
